// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "frontmatter": boolean;
      "fontSize": number;
      "whiteboardTutorialCreated": boolean;
      "shortcutNewStandaloneMd": string;
    };
  }
}
